apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: local-app
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: local/gateway:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 120m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: local-app
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 80

